---
# Main entry point for the home server setup
- name: Deploy Home Server Configuration
  hosts: home_servers
  become: true

  # We can define global variables here or in a separate file
  vars:
    setup_user: "{{ ansible_user }}"

  roles:
    - role: common
    - role: docker
    # The following role only runs if the hardware is a Raspberry Pi
    - role: raspberry_pi
      when: ansible_facts['board_name'] is search("Raspberry Pi")
    - role: storage
      when: 
        - storage_uuid is defined
        - storage_uuid | regex_search('^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$')