---
galaxy_info:
  role_name: zsh
  author: px1
  description: Install zsh with oh-my-zsh and custom plugins
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions: [bookworm, trixie]
  license: MIT
dependencies: []
