---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: debian
    image: geerlingguy/docker-debian12-ansible
    pre_build_image: true

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/..:${ANSIBLE_ROLES_PATH}"

verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - dependency
    - destroy
    - create
    - converge
    - idempotence
    - verify
    - destroy
